"""add category and status columns

Revision ID: 3de28ca678e9
Revises: 
Create Date: 2025-12-24 17:11:45.919734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de28ca678e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category', sa.String(), nullable=True))
    op.add_column('borrow_records', sa.Column('status', sa.String(), nullable=False))
    op.add_column('wishlist', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'category')
    op.drop_column('borrow_records', 'status')
    op.drop_column('books', 'category')
    # ### end Alembic commands ###
